export const inventory = [
    {
        categoryId: 1,
        id: '1',
        name: 'Floral Cardigan',
        price: 25.99,
        highlighted: true,
        mostSold: true,
        img: '../src/assets/Spring_/FloralCardigan.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '2',
        name: 'Shirt Jacket',
        price: 39.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Spring_/ShirtJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '3',
        name: 'Slim Jeans',
        price: 19.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Spring_/SlimJeans.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '4',
        name: 'Long Sleeve Top',
        price: 25.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Spring_/LongSleeveTop.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '5',
        name: 'Hooded Shirt Jacket',
        price: 49.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring_/HoodedShirtJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '6',
        name: 'Bomber Jacket',
        price: 49.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring_/BomberJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '7',
        name: 'Bermuda Shorts',
        price: 24.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring_/BermudaShorts.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '8',
        name: 'Daring T-Shirt',
        price: 7.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring_/DaringTShirt.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '9',
        name: 'Rain Jacket',
        price: 69.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring_/RainJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '10',
        name: 'Cotton Shirt Jacket',
        price: 34.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring_/CottonShirtJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '11',
        name: 'Denim Jacket',
        price: 27.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring_/DenimJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '12',
        name: 'Organic Cotton Shirt',
        price: 12.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring_/OrganicCottonShirt.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '13',
        name: 'Regular Fit Shirt',
        price: 19.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring_/RegularFitShirt.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },


    {
        categoryId: 2,
        id: '14',
        name: 'Crocheted Waistcoat',
        price: 39.99,
        highlighted: true,
        mostSold: true,
        img: '../src/assets/Summer_/CrochetedWaistcoat.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '15',
        name: 'Organic Cotton Dress',
        price: 22.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Summer_/OrganicCottonDress.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '16',
        name: 'T-Shirt Dress',
        price: 12.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Summer_/TShirtDress.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '17',
        name: 'Maternity Belt Dress',
        price: 29.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Summer_/MaternityBeltedDress.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '18',
        name: 'Cargo Trousers',
        price: 39.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer_/CargoTrousers.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '19',
        name: 'A-Line Dress',
        price: 29.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer_/ALineDress.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '20',
        name: 'Fit & Flare Dress',
        price: 69.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer_/FitnFlareDress.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '21',
        name: 'Cloth Trousers',
        price: 19.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer_/ClothTrousers.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '22',
        name: 'Crop Top',
        price: 9.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer_/CropTop.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '23',
        name: 'Clockhouse Hat',
        price: 9.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer_/ClockhouseHat.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '24',
        name: 'Cotton Belted Dress',
        price: 24.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer_/CrochetedWaistcoat.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '25',
        name: 'Linen Shirt',
        price: 19.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer_/LinenShirt.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '26',
        name: 'Polo Shirt',
        price: 12.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer_/PoloShirt.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },


    {
        categoryId: 3,
        id: '27',
        name: 'Trench Coat',
        price: 69.99,
        highlighted: true,
        mostSold: true,
        img: '../src/assets/Autumn_/TrenchCoat.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '28',
        name: 'Flannel Shirt',
        price: 25.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Autumn_/FlannelShirt.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '29',
        name: 'Straight Jeans',
        price: 49.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Autumn_/StraightJeans.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '30',
        name: 'Cashmere Slipover',
        price: 79.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Autumn_/CashmereSlipover.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '32',
        name: 'Fleece Gilet',
        price: 29.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn_/FleeceGilet.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '53',
        name: 'Long Coat',
        price: 79.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn_/LongCoat.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '33',
        name: 'Kent Collar Shirt',
        price: 25.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn_/KentCollarShirt.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '34',
        name: 'Zip-through Sweatshirt',
        price: 25.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn_/ZipThroughSweatshirt.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '35',
        name: 'Organic Cotton Jumper',
        price: 19.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn_/OrganicCottonJumper.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '36',
        name: 'Organic Cotton Hoodie',
        price: 25.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn_/OrganicCottonHoodie.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '37',
        name: 'Corduroy Trousers',
        price: 39.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn_/CorduroyTrousers.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '38',
        name: 'Knitted Cardigan',
        price: 17.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn_/KnittedCardigan.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '39',
        name: 'Polo Neck Top',
        price: 15.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn_/PoloTurtleNeck.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },


    {
        categoryId: 4,
        id: '40',
        name: 'Parca Faux Fur',
        price: 79.99,
        highlighted: true,
        mostSold: true,
        img: '../src/assets/Winter__/ParcaFauxFur.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '41',
        name: 'Wool Jumper',
        price: 29.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Winter_/WoolJumper.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '42',
        name: 'Fleece Jacket',
        price: 29.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Winter_/Fleecejacke.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '43',
        name: 'Fingerless Gloves',
        price: 7.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Winter_/FingerlessGloves.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '44',
        name: 'Fringed Scarf',
        price: 19.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter_/FringedScarf.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '45',
        name: 'Knitted Hat',
        price: 9.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter_/KnittedHat.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '46',
        name: 'Wool Hat',
        price: 7.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter_/WoolHat.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '47',
        name: 'Quilted Coat',
        price: 79.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter_/QuiltedCoat.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '48',
        name: 'Quilted Gloves',
        price: 12.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter_/QuiltedGloves.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '49',
        name: 'Polar Jacket',
        price: 99.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter_/PolarJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '50',
        name: 'X Jumper',
        price: 19.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter_/XJumper.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '51',
        name: 'Markes Jacket',
        price: 129.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter_/MarkesJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '52',
        name: 'Snow Jacket',
        price: 99.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter_/SnowJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
]