export const inventory = [
    {
        categoryId: 1,
        id: '1',
        name: 'Floral Cardigan',
        price: 25.99,
        highlighted: true,
        mostSold: true,
        img: '../src/assets/Spring/FloralCardigan.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '2',
        name: 'Shirt Jacket',
        price: 39.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Spring/ShirtJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '3',
        name: 'Slim Jeans',
        price: 19.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Spring/SlimJeans.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '4',
        name: 'Long Sleeve Top',
        price: 25.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Spring/LongSleeveTop.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '5',
        name: 'Hooded Shirt Jacket',
        price: 49.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring/HoodedShirtJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '6',
        name: 'Bomber Jacket',
        price: 49.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring/BomberJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '7',
        name: 'Bermuda Shorts',
        price: 24.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring/BermudaShorts.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '8',
        name: 'Daring T-Shirt',
        price: 7.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring/DaringTShirt.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '9',
        name: 'Rain Jacket',
        price: 69.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring/RainJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '10',
        name: 'Cotton Shirt Jacket',
        price: 34.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring/CottonShirtJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '11',
        name: 'Denim Jacket',
        price: 27.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring/DenimJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '12',
        name: 'Organic Cotton Shirt',
        price: 12.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring/OrganicCottonShirt.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 1,
        id: '13',
        name: 'Regular Fit Shirt',
        price: 19.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Spring/RegularFitShirt.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },


    {
        categoryId: 2,
        id: '14',
        name: 'Crocheted Waistcoat',
        price: 39.99,
        highlighted: true,
        mostSold: true,
        img: '../src/assets/Summer/CrochetedWaistcoat.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '15',
        name: 'Organic Cotton Dress',
        price: 22.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Summer/OrganicCottonDress.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '16',
        name: 'T-Shirt Dress',
        price: 12.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Summer/TShirtDress.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '17',
        name: 'Maternity Belt Dress',
        price: 29.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Summer/MaternityBeltedDress.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '18',
        name: 'Cargo Trousers',
        price: 39.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer/CargoTrousers.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '19',
        name: 'A-Line Dress',
        price: 29.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer/ALineDress.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '20',
        name: 'Fit & Flare Dress',
        price: 69.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer/FitnFlareDress.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '21',
        name: 'Cloth Trousers',
        price: 19.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer/ClothTrousers.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '22',
        name: 'Crop Top',
        price: 9.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer/CropTop.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '23',
        name: 'Clockhouse Hat',
        price: 9.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer/ClockhouseHat.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '24',
        name: 'Cotton Belted Dress',
        price: 24.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer/CrochetedWaistcoat.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '25',
        name: 'Linen Shirt',
        price: 19.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer/LinenShirt.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 2,
        id: '26',
        name: 'Polo Shirt',
        price: 12.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Summer/PoloShirt.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },


    {
        categoryId: 3,
        id: '27',
        name: 'Trench Coat',
        price: 69.99,
        highlighted: true,
        mostSold: true,
        img: '../src/assets/Autumn/TrenchCoat.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '28',
        name: 'Flannel Shirt',
        price: 25.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Autumn/FlannelShirt.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '29',
        name: 'Straight Jeans',
        price: 49.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Autumn/StraightJeans.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '30',
        name: 'Cashmere Slipover',
        price: 79.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Autumn/CashmereSlipover.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '32',
        name: 'Fleece Gilet',
        price: 29.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn/FleeceGilet.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '53',
        name: 'Long Coat',
        price: 79.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn/LongCoat.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '33',
        name: 'Kent Collar Shirt',
        price: 25.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn/KentCollarShirt.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '34',
        name: 'Zip-through Sweatshirt',
        price: 25.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn/ZipThroughSweatshirt.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '35',
        name: 'Organic Cotton Jumper',
        price: 19.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn/OrganicCottonJumper.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '36',
        name: 'Organic Cotton Hoodie',
        price: 25.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn/OrganicCottonHoodie.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '37',
        name: 'Corduroy Trousers',
        price: 39.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn/CorduroyTrousers.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '38',
        name: 'Knitted Cardigan',
        price: 17.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn/KnittedCardigan.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 3,
        id: '39',
        name: 'Polo Neck Top',
        price: 15.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Autumn/PoloTurtleNeck.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },


    {
        categoryId: 4,
        id: '40',
        name: 'Parca Faux Fur',
        price: 79.99,
        highlighted: true,
        mostSold: true,
        img: '../src/assets/Winter/ParcaFauxFur.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '41',
        name: 'Wool Jumper',
        price: 29.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Winter/WoolJumper.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '42',
        name: 'Fleece Jacket',
        price: 29.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Winter/Fleecejacke.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '43',
        name: 'Fingerless Gloves',
        price: 7.99,
        highlighted: true,
        mostSold: false,
        img: '../src/assets/Winter/FingerlessGloves.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '44',
        name: 'Fringed Scarf',
        price: 19.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter/FringedScarf.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '45',
        name: 'Knitted Hat',
        price: 9.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter/KnittedHat.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '46',
        name: 'Wool Hat',
        price: 7.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter/WoolHat.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '47',
        name: 'Quilted Coat',
        price: 79.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter/QuiltedCoat.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '48',
        name: 'Quilted Gloves',
        price: 12.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter/QuiltedGloves.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '49',
        name: 'Polar Jacket',
        price: 99.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter/PolarJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '50',
        name: 'X Jumper',
        price: 19.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter/XJumper.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '51',
        name: 'Markes Jacket',
        price: 129.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter/MarkesJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
    {
        categoryId: 4,
        id: '52',
        name: 'Snow Jacket',
        price: 99.99,
        highlighted: false,
        mostSold: false,
        img: '../src/assets/Winter/SnowJacket.png',
        description: 'Lorem Ipsum...',
        sizeQty: { S: 2, M: 3, XL: 4 }
    },
]